### ISSUE TITLE
Admin Approval - Email Notifications

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#121]
Articles & Discussions 
this two things Admin need to approve ...so can we have a Email notification system for Admin...
so that whenever a new Article or Discussion added by user a email should come to Admin so that he can approve it on time.

Even notification in his Fitrangi account profile should come..

can this facility is possible ?

**Comment by arshadansari27** [comment]
It is possible... let me look into this

**Comment by YunusDange** [comment]
What solution e found for this..? 
i have not received mails after used added any discussion

**Comment by YunusDange** [comment]
Is this solved...
On which ID i will receive Email Notifications ? & When?

**Comment by YunusDange** [comment]
Is this solved...
On which ID i will receive Email Notifications ? & When?

**Comment by arshadansari27** [comment]
It is solved... fitrangi@gmail.com or yunusdange@gmail.com

please check your spam too, if you are not seeing it.. coz I'm also getting them..

**Comment by YunusDange** [comment]
Not getting it..checked everything..

don't add yunusdange@gmail.com 

just add fitrangi@gmail.com

**Comment by arshadansari27** [comment]
it was coming only to me.. we all are admin, it was sending to the first one it use to fetch.. not it will send to all admins.

**Comment by YunusDange** [comment]
I Still don't see it's working

i have added one discussion through a normal profile...

see if you received a mail or not....as i have not received

**Comment by arshadansari27** [comment]
Can you test this again... create a new content and then publish it...

**Comment by YunusDange** [comment]
i have posted both...Discussion and Blog.....not received any mail yet....
waiting for it

**Comment by arshadansari27** [comment]
Im not recieving any email at all... i think something isnwrong with mailing functionality... i ll figure out

**Comment by arshadansari27** [comment]
I think the mail sender has blocked us, since few spam emails were sent... those bots were testing by creating fake profiles.. I think those fake registrations caused mails to be sent to fake ids, which must be blocked... I should look into it now..

**Comment by arshadansari27** [comment]
Are you getting these emails? @YunusDange

**Comment by YunusDange** [comment]
No....not getting any emails...checked once again

**Comment by YunusDange** [comment]
Is this issue solved...?
how much time it will take...? we will need this now...desperately :)

**Comment by arshadansari27** [comment]
I think this is solved. This email issue was the reason why we were getting failure message on publishing even when it was publishing the content. This was causing the mails to not be sent. Since the same method is used to approve content as well as discussion, it was failing for both.

Test this and close it if its working.

**Comment by YunusDange** [comment]
Keep this open....although i can see some emails but i have not received emails for new testing content i have just posted...so i will test it today entire day and see whether it's working properly or now

**Comment by arshadansari27** [comment]
I got three such emails...

**Comment by YunusDange** [comment]
yes..i also got that now..so i think it's working for Post approval now...

but not working for others like
1) Business Profile Listing (when someone create a business profile)
2) When someone claimed a particular business profile
3) When Someone Flagged any content
4)
