### ISSUE TITLE
Social Sharing - Thumbnail View Issue

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#192]
When we share any Discussion, Blog, Adventure....or even Main website link...the thumbnail it creates is not proper.....

we have cover image in almost all the sections as well as in all the content............... that is our main structure..

so there is a way....we can make this thumbnail to be that cover image for every link...?

![screenshot-2015-05-25-22 02 49](https://cloud.githubusercontent.com/assets/7126709/7799898/498d462e-032a-11e5-80f2-93a0444ce8ee.jpg)

let me know if you don't understand the issue

**Comment by arshadansari27** [comment]
you mean sharing to fb gplus etc? 

i dont have control over how they choose thumbnail content.. if there is any guidelines to follow in design to get them to choose right thumbnail, let me check.. we can implement that... but not in this milestone

**Comment by arshadansari27** [comment]
i got an idea though.. let me test that...

**Comment by YunusDange** [comment]
not exactly that...i am talking about directly copy pasting the URLs to facebook post...but i think...the issue will remain the same in both the case..

**Comment by arshadansari27** [comment]
i knw what ur saying... the reason we are not getting the right cover image is because we r not using image tag for cover image.. its a bg for title container... there an image tag for ajax loading.. so fb thinks thats the main page image... ill put cover image separately on the same page in hidden mode so it is selected

**Comment by YunusDange** [comment]
Okkz...but what about content...articles...blogs and discussions.....we
can't do this for them always...need to find some fix solution for
this...as it will be our biggest weapon in promotion..

**Comment by arshadansari27** [comment]
Works ok on google plus... but on facebook it doest.. need to find out why.. changing milestone.. its become bit of bug hunting...

**Comment by arshadansari27** [comment]
seeems like facebook has cached a default image for our site... so it must be using that.. let's test it tomorrow and see if it works..

**Comment by arshadansari27** [comment]
can u test this... seems to be working now

**Comment by YunusDange** [comment]
Not working properly...

Only in case of activity pages a thumbnail get generated that is also a homepage images and not related activity image

**Comment by arshadansari27** [comment]
can u explain that better? i didnt understand ... what part is working and
what part is not?

**Comment by YunusDange** [comment]
Thumbnail are not working at all

But
Whenever i share any activity page then there is a thumbnail image.......but that image is same for all activities (Homepage Cover Image)

call me if doesn't understand

**Comment by arshadansari27** [comment]
Can u test this once again?

**Comment by arshadansari27** [comment]
I think its fixed now...

**Comment by YunusDange** [comment]
I don't think it's working...even tried in private window
see below
![screenshot-2015-06-05-18 41 52](https://cloud.githubusercontent.com/assets/7126709/8006733/fc25fe48-0bb3-11e5-8feb-7816629fb5f2.jpg)

![screenshot-2015-06-05-18 42 09](https://cloud.githubusercontent.com/assets/7126709/8006734/ff746724-0bb3-11e5-8d38-e7b1b0298a43.jpg)
![screenshot-2015-06-05-18 42 42](https://cloud.githubusercontent.com/assets/7126709/8006735/05dd8ec4-0bb4-11e5-8a6d-58a804b8708a.jpg)

**Comment by arshadansari27** [comment]
I thought we wanted it for detail view only.. It will work in detail view only.. The last image you uploaded there about hot air ballon, can u check what happens after you post? Coz it showed similarly to me, but after posting, it showed the image...

**Comment by YunusDange** [comment]
i think this ticket should be open...THUMBNAILS are working only in case of Adventures
Homepage, Blogs & other areas are still not working

**Comment by arshadansari27** [comment]
THis is the way I have fixed it:

Home Page, and all landing pages have a common thumbnail.
All Detail Pages have specific thumbnails. I think that would suffice for now. If yes, then let's close this ticket...

If that is not solved then keep this open as is. 

If Solved, but the search pages should also become specific, then also we can keep this open but with a different, less urgent, label attached to it.

**Comment by YunusDange** [comment]
I think the way you have fixed it..will solve the purpose for now..
BUT
it is not working as you describe..

NOT WORKING at All : Home Page, and all landing pages have a common thumbnail.
WORKING Some time,,NOT WORKING sometime:  All Detail Pages have specific thumbnails. 

Please share screenshots if it is working on yourside

**Comment by arshadansari27** [comment]
Just one question..

Is the detail view working all the time or even that is screwed up sometimes?
Is the home page working all the time or is it screwed up too sometimes?
Rest of the pages were low on priority anyways for now....

**Comment by YunusDange** [comment]
Homepage is not at all working

Details pages screwed more time than it works...means work sometime
